id: P2A8242B6
initial_creation_type: input
source_metadata:
  title: Paramārthasāra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: Daniele Cuneo
  contribution to GRETIL: Daniele Cuneo
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:53:50.901652'
last_modified_at: '2022-03-09T14:53:50.901664'
